# Generated by Django 2.1 on 2018-11-27 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(db_index=True)),
            ],
            options={
                'db_table': 'bible_book',
            },
        ),
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_nb', models.IntegerField()),
                ('verse', models.TextField()),
            ],
            options={
                'db_table': 'saint',
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('verse_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('verse_nb', models.IntegerField(db_index=True)),
                ('text', models.TextField()),
                ('text_introductory', models.TextField()),
                ('text_ending', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatitud_corpus.Book')),
            ],
            options={
                'db_table': 'bible_verse',
            },
        ),
    ]
