version: '2.2'

services:

  django:
    build: .
    restart: always
    container_name: beatitud_back_django
    env_file:
      - env/django_variables.env
      - env/db_postgres_variables.env
      - env/elasticsearch_variables.env
    volumes:
    - ./beatitud_back:/home/django/webapp/beatitud_back
    - ./apps:/home/django/webapp/apps
    ports:
      - '8000:8000'
    command: /usr/bin/python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:10.5-alpine
    container_name: beatitud_postgres
    restart: always
    env_file:
      - ./env/db_postgres_variables.env
    ports:
      - '5432:5432'
    volumes:
    - db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: beatitud_elasticsearch
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - elasticsearch:/home/django/eslasticsearch
    ports:
    - '9200:9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.2
    container_name: beatitud_kibana
    volumes:
    - ./apps/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
    - '5601:5601'

volumes:
  db:
  elasticsearch:
  kibana:

