version: '3'

services:
  django:
    build: .
    env_file:
      - env/django_variables.env
      # We need those to configure default db of django
      - env/db_postgres_variables.env
    volumes:
      # Useful in order not to give in the container a lot of useless files that we already wanted to ignore in the dockerignore
    - ./beatitud_back:/home/django/webapp/beatitud_back
    - ./apps:/home/django/webapp/apps
    ports:
      - '8000:8000'
    command: /usr/bin/python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:10.5-alpine
    restart: always
    env_file:
      - ./env/db_postgres_variables.env
    ports:
      - '5432:5432'
    volumes:
    - db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db:

